from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ..models import RemoteHead, SnapshotManifest


class StorageProvider(Protocol):
    def baseline_ids(self) -> list[str]: ...
    def upload_baseline(self, artifact: Path, manifest: SnapshotManifest) -> None: ...
    def upload_version(self, artifact: Path, manifest: SnapshotManifest) -> None: ...
    def download_artifact(self, artifact_id: str, destination: Path) -> None: ...
    def read_head(self) -> RemoteHead | None: ...
    def update_head(self, expected_version: str | None, head: RemoteHead) -> None: ...
    def list_versions(self) -> list[RemoteHead]: ...
